### ISSUE TITLE
Cluster annotation file

### ISSUE THREAD

**Issue by jchang97** [LuyiTian/FLAMES#19]
Hi there,

Thank you for creating this amazing tool! 

I am trying to utilize the DTU analysis script from the FLTseq_data directory, and I am just wondering how I can get the **cluster_annotation.csv** file? 

(Line 80-82)
```
cluster_barcode_anno <- read.csv(file.path(data_dir,"cluster_annotation.csv"), stringsAsFactors=FALSE)
  rownames(cluster_barcode_anno) = cluster_barcode_anno$barcode_seq
  comm_cells = intersect(colnames(tr_sce),rownames(cluster_barcode_anno))
```

Thank you

**Comment by LuyiTian** [comment]
that is a file you generated from analyzing short-read data. so basically you analyse short-read data first and generate either cell type annotation or cluster id. then these categories will be used for DTU analysis as the input of groups.

**Comment by LuyiTian** [comment]
if you want some example here are the data associated with the paper: https://github.com/LuyiTian/FLTseq_data/tree/master/data which includes the cluster_annotation.csv file

**Comment by jchang97** [comment]
Thank you so much!
