### ISSUE TITLE
empty transcript_assembly.fa file using example SIRV data

### ISSUE THREAD

**Issue by luiseze** [LuyiTian/FLAMES#25]
Hi,
I tried running the example in the example folder of the python installation of FLAMES which gives an error:
`subprocess.CalledProcessError: Command '['samtools faidx FLAMES_output/transcript_assembly.fa']' returned non-zero exit status 1.`
I noticed that the transcript_assembly.fa file is empty. In the get_transcript_seq function in gff3_to_fa.py, it exits the first for loop right away as the following statement is false: `if ch not in chr_to_gene:`. However, it also does not enter the next for loop (`for tr_seq in global_seq_dict:`) because the dictionary is empty. I'd really appreciate your help.

**Comment by ChangqingW** [comment]
Seems like it's due to wrong mode used in `gzip.open`, should be fixed by 54be4e0ab4c7ef43795ea523afa5f3e805fb646c .
