### ISSUE TITLE
Source compilation errror

### ISSUE THREAD

**Issue by lingminhao** [LuyiTian/FLAMES#33]
Hi @LuyiTian , I am currently using FLAMES for single cell isoform identification and detection. Now I'm at the barcode assignment steps, where I ran the compilation code `g++ -std=c++11 -lz -O2 -o match_cell_barcode ssw/ssw_cpp.cpp ssw/ssw.c match_cell_barcode.cpp kseq.h edit_dist.cpp` as shown in the README, but I get the following error: 

![image](https://user-images.githubusercontent.com/53725270/205230960-8a39f840-a2d9-4872-b77b-0b5b68c99ed6.png)

What is the problem?

**Comment by sonalhenson** [comment]
@lingminhao , did you resolve this error? Asking as I'm facing the same error and would welcome suggestions on how to fix it.
Thanks
