### ISSUE TITLE
No output from match_cell_barcode

### ISSUE THREAD

**Issue by LI-Yan-Ming** [LuyiTian/FLAMES#36]
Hi,

Thank you for sharing FLAMES!

I think I have successfully run the match_cell_barcode as I got the information pasted below.
![image](https://user-images.githubusercontent.com/61558240/211134555-b54c71e6-b178-490e-bf31-1a908b5f7a77.png)
![image](https://user-images.githubusercontent.com/61558240/211134578-8bbcc51c-3222-4d2b-a025-24a1ef6300a0.png)

However, I didn't get any output, neither matched fastq nor barcode statistic. Can you please comment on that?

Many thanks!
Yanming

**Comment by LuyiTian** [comment]
`usage: <1.fastq folder> <2.output cell barcode statistics file> <3.fastq output reads that matched cell barcode> <4.barcode reference from short read 10X data> <5.max edit distance> [6. UMI length (default: 10)].` I think the third parameter need to be a file name. and I would recommand you use absolute file path all the time.
