### ISSUE TITLE
match_cell_barcode - output cell barcode statistics file

### ISSUE THREAD

**Issue by maegsul** [LuyiTian/FLAMES#38]
Hi, I am using match_cell_barcode for ONT single cell data. I obtained a "whitelist.csv" and "putative_bc.csv" file from the output of [BLAZE](https://github.com/shimlab/BLAZE), at the same time I also have short-read sequencing data on the same library.

However, I am confused what file should be used for the 2nd argument of match_cell_barcode, that is "output cell barcode statistics file", or as explained in README "a file name/path for the statistics of barcode matching". 

Can you please help with understanding this file? How should it look like (which headers?) and how can I get it?

Thanks in advance!

**Comment by LuyiTian** [comment]
it should be an output file. so you just need to give a file path that the program have write access to.

**Comment by maegsul** [comment]
Thank you very much, this makes sense! :)
