### ISSUE TITLE
FLAMES vs FLAIR

### ISSUE THREAD

**Issue by danledinh** [LuyiTian/FLAMES#8]
I'm evaluating FLAMES and FLAIR for my project. Can you comment on the conceptual or algorithmic differences between the two packages? For example, what aspect of FLAMES leads to its increased accuracy in benchmarking?

**Comment by LuyiTian** [comment]
One difference is that FLAMES does not really trust a single read, instead it group reads to achieve a consensus isoform. It will make the method more robust but less sensitive to very rare novel isoforms. basically it is a trade-off.
